#!/usr/bin/env bash

task-flyway() {
    stage=$1

    if [[ $stage != "dev" && $stage != "prod" ]]; then
        echo "Usage: kar flyway <stage> command ... "
        exit 1
    elif [[ $stage == "dev" ]]; then
        dbname=devarticlerecdb
    elif [[ $stage == "prod" ]]; then
        dbname=articlerecdb
        echo "WARNING: running on prod!!!"
    fi

    shift 1

    user=$(ssm get /$stage/database/user)
    host=$(ssm get /$stage/database/host)
    password=$(ssm get /$stage/database/password)
    jdbc_uri="jdbc:postgresql://$host/$dbname?user=$user&password=$password"
    flyway -url=$jdbc_uri -locations="filesystem:$(pwd)/migrations" $@
}


task-connect() {
    stage=$1

    if [[ $stage != "dev" && $stage != "prod" ]]; then
        echo "Usage: kar flyway <stage> command ... "
        exit 1
    elif [[ $stage == "dev" ]]; then
        db_uri=$(ssm get /dev/database/uri)
    elif [[ $stage == "prod" ]]; then
        db_uri=$(ssm get /prod/database/uri)
        echo "WARNING: connecting to prod!!!"
    fi

    shift 1

    psql $db_uri
}