"""column changes following pydantic upgrade to 2.0

Revision ID: 70e5e82e94c0
Revises: 46c271f8f06f # noqa: W291
Create Date: 2023-12-04 16:19:45.970626

"""
import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "70e5e82e94c0"
down_revision = "46c271f8f06f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("article", "site", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("embedding", "vector", existing_type=pgvector.sqlalchemy.Vector(dim=384), nullable=False)
    op.alter_column("page", "url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("page", "url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("embedding", "vector", existing_type=pgvector.sqlalchemy.Vector(dim=384), nullable=True)
    op.alter_column("article", "site", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
