"""add execution and embedding tables

Revision ID: 02e515c5bb2a
Revises: a7616acbfe1c # noqa: W291
Create Date: 2023-11-09 20:31:18.097158

"""
import pgvector
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "02e515c5bb2a"
down_revision = "a7616acbfe1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "strategy",
            sa.Enum("POPULARITY", "COLLABORATIVE_FILTERING_ITEM_BASED", "SEMANTIC_SIMILARITY", name="strategytype"),
            nullable=False,
        ),
        sa.Column("db_created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "embedding",
        sa.Column("vector", pgvector.sqlalchemy.Vector(dim=384), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("db_created_at", sa.DateTime(), nullable=False),
        sa.Column("article_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.page_id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["execution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("embedding")
    op.drop_table("execution")
    # ### end Alembic commands ###
