"""add more article fields

Revision ID: 1feba14fd658
Revises: 70e5e82e94c0 # noqa: W291
Create Date: 2023-12-04 20:10:13.657413

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1feba14fd658"
down_revision = "70e5e82e94c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("article", sa.Column("content", sa.Text(), nullable=False))
    op.add_column("article", sa.Column("site_published_at", sa.DateTime(), nullable=False))
    op.add_column("article", sa.Column("site_updated_at", sa.DateTime(), nullable=True))
    op.drop_column("article", "published_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column("article", "site_updated_at")
    op.drop_column("article", "site_published_at")
    op.drop_column("article", "content")
    op.drop_column("article", "description")
    # ### end Alembic commands ###
