"""remove article_exclude_reason field from page table and add new article fields

Revision ID: 46c271f8f06f
Revises: e8f9a954be12 # noqa: W291
Create Date: 2023-12-04 13:38:09.372485

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "46c271f8f06f"
down_revision = "e8f9a954be12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("ENGLISH", "SPANISH", name="language").create(op.get_bind())
    op.add_column(
        "article",
        sa.Column("language", postgresql.ENUM("ENGLISH", "SPANISH", name="language", create_type=False), nullable=False),
    )
    op.add_column("article", sa.Column("is_in_house_content", sa.Boolean(), nullable=False))
    op.drop_column("page", "article_exclude_reason")
    sa.Enum("NOT_ARTICLE", "NOT_IN_HOUSE_ARTICLE", "TEST_ARTICLE", "HAS_EXCLUDED_TAG", name="articleexcludereason").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "NOT_ARTICLE", "NOT_IN_HOUSE_ARTICLE", "TEST_ARTICLE", "HAS_EXCLUDED_TAG", name="articleexcludereason"
    ).create(op.get_bind())
    op.add_column(
        "page",
        sa.Column(
            "article_exclude_reason",
            postgresql.ENUM(
                "NOT_ARTICLE",
                "NOT_IN_HOUSE_ARTICLE",
                "TEST_ARTICLE",
                "HAS_EXCLUDED_TAG",
                name="articleexcludereason",
                create_type=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("article", "is_in_house_content")
    op.drop_column("article", "language")
    sa.Enum("ENGLISH", "SPANISH", name="language").drop(op.get_bind())
    # ### end Alembic commands ###
