"""remove score 0-1 constraint

Revision ID: 83af0e3a4df3
Revises: 1c865617a68f # noqa: W291
Create Date: 2024-01-17 10:15:42.344551

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "83af0e3a4df3"
down_revision = "1c865617a68f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recommendation_score_between_0_and_1", "recommendation", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("recommendation_score_between_0_and_1", "recommendation", "score >= 0 AND score <= 1")
    # ### end Alembic commands ###
