name: publish
on:
  push:
    branches:
      - dev # dev acts as the default branch for package version updates, for now
    paths:
      - "pyproject.toml"
jobs:
  build-publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.7.0
      - name: Publish package
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}
